### ISSUE TITLE
Fix spec related files

### ISSUE THREAD

**Issue by chalin** [DarikshaAnsari/in-toto-docs#13]
_Originally posted by @chalin in https://github.com/DarikshaAnsari/in-toto-docs/pull/7#pullrequestreview-2206127500_

### One main issue remains regarding the specs page.

What you **should** have in this PR is the following:

- `data/specs.yaml` - same as the current site
- `layouts/shortcodes/spec-table.md` - shortcode that generates the specs table in Markdown; it will be very similar to the current site's `layouts/shortcodes/specs.html` shortcode, but will use Makrdown instead of HTML in the shortcode. If you can't figure this out, embed the hardcoded table for now and I'll show you how we can do this in a followup PR.
- `content/en/docs/specs.md` - a page that simply references the shortcode using `{{% spec-table %}}`.

**Comment by DarikshaAnsari** [comment]
@chalin I think this issue is already resolved in #9. Can I close this issue ??

**Comment by chalin** [comment]
> @chalin I think this issue is already resolved in #9. Can I close this issue ??

No, it cannot be closed because it has _not_ been resolved. Let me explain.

For example, in the opening comment to the issue, the first bullet says that there **should be a file named `data/specs.yaml`** in this repo.

But if you look in https://github.com/DarikshaAnsari/in-toto-docs/tree/main/data, **there is no such file at the moment** (see the image below), so **why do you feel that this has been resolved**?

Similar comments apply to the other two files that are currently not a part of this repo.

---

> <img width="500" alt="image" src="https://github.com/user-attachments/assets/cbcffa88-ef8d-46c7-b1e2-e1942391b14f">
