### ISSUE TITLE
Specifications page: make the table look like the original site

### ISSUE THREAD

**Issue by chalin** [DarikshaAnsari/in-toto-docs#15]
Change the specifications table to look like this (with only **two columns**) -- from https://in-toto.io/specs/:

> <img width="938" alt="image" src="https://github.com/user-attachments/assets/4c98d4f5-b716-484e-b35c-f9d768aa003d">

rather than what it currently is:

> <img width="1073" alt="image" src="https://github.com/user-attachments/assets/ae005478-7b20-4971-a245-0f148549716a">

**Comment by DarikshaAnsari** [comment]
You have given this review **[here](https://github.com/DarikshaAnsari/in-toto-docs/pull/7#discussion_r1690606051)** in this discussion.

**Comment by chalin** [comment]
Right, but if you look closely, my comment was made over the **data file**,  **_not_ the rendering of the table in the page**. Do you see that now?

> ![image](https://github.com/user-attachments/assets/d36090d1-54f1-4441-8a65-652705045170)
