### ISSUE TITLE
Setup Docsy as a submodule linking to the latest official release

### ISSUE THREAD

**Issue by chalin** [DarikshaAnsari/in-toto-docs#3]
Currently `themes/docsy` contains a copy of the Docsy repo files. That shouldn't be the case. Instead, setup the use of Docsy via a Git submodule.

**Comment by DarikshaAnsari** [comment]
![image](https://github.com/DarikshaAnsari/in-toto-docs/assets/100822529/59540bd3-0b58-4043-a29b-a3c1336c86d2)
```
PS C:\Users\asus\OneDrive\Documents\Opensource\myproject> git submodule status
>>
 309da207e5deeda762348bfd0cc32367c5565a1e themes/docsy (v0.10.0-16-g309da20)
```

**Comment by chalin** [comment]
Well done. Closing since this has been fixed.
