### ISSUE TITLE
Create a more standard-Docsy homepage

### ISSUE THREAD

**Issue by chalin** [DarikshaAnsari/in-toto-docs#4]
Create a more standard-Docsy homepage for this version of the website. The homepage should look similar to this one for example:

- https://opentelemetry.io

You can find the page source for the site's homepage in the OTel website repo. You can also look at other examples for inspiration, such as https://example.docsy.dev.

**Comment by chalin** [comment]
You can also look at other examples for inspiration, such as https://example.docsy.dev.

**Comment by chalin** [comment]
See https://opentelemetry.io/ for an example of how to fix the following:

- [x] The top-nav logo:
  <img width="195" alt="image" src="https://github.com/DarikshaAnsari/in-toto-docs/assets/4140793/1721c74d-1245-4817-b9c1-b14d4060cd4e">
- [x] The hero image should be about the same size as for the existing website (the green box in the image below), see the OTel website for an example since it has a hero image that is of about the right size as what you need for in-toto:
  > ![image](https://github.com/DarikshaAnsari/in-toto-docs/assets/4140793/32f035d9-6c4b-4fb3-9530-4d8644fbf270)
- [x] Fix the three **Read more** link targets (e.g., one of them links to Docsy :). The links should be the same as the existing in-toto website

**Comment by DarikshaAnsari** [comment]
@chalin Fixed the top nav bar as suggested only used logo with default title instead with wordmark. I have searched a lot about how can i change hero image but didnt get anything in layout so that i can change css of that particular block.

**Comment by DarikshaAnsari** [comment]
And in last point are you talking about the learn more button in in-toto.io 
![image](https://github.com/user-attachments/assets/e707828b-755d-4e71-b890-14ae51a77722)

**Comment by chalin** [comment]
> @chalin Fixed the top nav bar as suggested only used logo with default title instead with wordmark. I have searched a lot about how can i change hero image but didnt get anything in layout so that i can change css of that particular block.

I'm not seeing that fixed in the preview, but I'll let Lukas review this next week.

As for the last point, I'm referring to these "Read more" links:

> <img width="1546" alt="image" src="https://github.com/user-attachments/assets/d5928334-ebda-4efa-8b7e-4c5cf6b62246">

**Comment by chalin** [comment]
> @chalin ... I have searched a lot about how can i change hero image but didnt get anything in layout so that i can change css of that particular block.

Try changing `height` to `max` in the following:

<pre>
{{% blocks/cover <del>title="Welcome to in-toto!"</del> image_anchor="top" <b>height="max"</b> %}}
</pre>

Also, drop the `title` field as shown above. Instead, include the logo+wordmark just like the current site has. You can see how this was done for the OTel website here: https://github.com/open-telemetry/opentelemetry.io/blame/dc79770a701688205fd4b82532cf66ee5233ecaa/content/en/_index.md#L19-L25

**Comment by DarikshaAnsari** [comment]
@chalin refer to this link as preview link https://main--in-toto-docs.netlify.app/

**Comment by chalin** [comment]
The points raised in the second comment have all been address. Well done @DarikshaAnsari. Closing as done.
