### ISSUE TITLE
Convert `config.toml` to `hugo.yaml`

### ISSUE THREAD

**Issue by chalin** [DarikshaAnsari/in-toto-docs#5]

**Comment by DarikshaAnsari** [comment]
Hey @chalin , I am not working on this now as Lukas told me to raise a PR  to setup docsy theme in in-toto.io.

**Comment by chalin** [comment]
Please address this issue before we migrate to the in-toto website repo.

**Comment by DarikshaAnsari** [comment]
hey @chalin I have already resolved this issue and converted config.toml to hugo.yaml
