### ISSUE TITLE
Misc comments

### ISSUE THREAD

**Issue by lukpueh** [DarikshaAnsari/in-toto-docs#8]
- I like that the buttons and links on the landing page navigate to subpages inside docs. Maybe we can make this more consistent. That is, we map all buttons/links on the landing page to subpages . E.g. we could make "demo" and "friends"   subpages in docs, to which "Try the demo" and "Explore integrations" point to. Those pages can then contain a short description of demo and friends repos and pointers to those repos. I think that might be a less disruptive experience, compared to when the user is directed to external pages right away on the landing page.

- Why are there two search bars, one in the right top corner and one in the left navigation column? (no need to fix this now, I'm just curious)

- Regarding content I am not sure if we should follow the recommendation from the [cncf assessment](https://github.com/in-toto/in-toto.io/issues/35) and just re-publish the docs from python-in-toto as Getting started page. The documentation should represent the whole in-toto project, but the python-in-toto cli is only one of multiple in-toto implementations.

_Originally posted by @lukpueh in https://github.com/DarikshaAnsari/in-toto-docs/issues/7#issuecomment-2252204008_

**Comment by chalin** [comment]
> * Why are there two search bars, one in the right top corner and one in the left navigation column? (no need to fix this now, I'm just curious)

@lukpueh - that's styling error in this repo. The search bar in the left nav should only appear when the top-nav search bar disappears -- on mobile or narrow displays. For an example of this behavior, see https://opentelemetry.io/docs/.

> * Regarding content I am not sure if we should follow the recommendation from the [cncf assessment](https://github.com/in-toto/in-toto.io/issues/35) and just re-publish the docs from python-in-toto as Getting started page. The documentation should represent the whole in-toto project, but the python-in-toto cli is only one of multiple in-toto implementations.

Agreed.

**Comment by chalin** [comment]
> @lukpueh - that's styling error in this repo. The search bar in the left nav should only appear when the top-nav search bar disappears -- on mobile or narrow displays. For an example of this behavior, see https://opentelemetry.io/docs/.

Actually, I take that back, it seems to be the Docsy default styling. @DarikshaAnsari - see the OTel website repo styles to learn how to hide the sidenav search when the top-nav search is showing.
